config/routes.rb
TodoList::Application.routes.draw do
  resources :todolists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todolists#index'

  

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todolist

  validates :content, presence: true
  validates :content, length: {minimum: 3}

  scope :complete, -> {where('completed_at is not null')}
  scope :incomplete, -> {where(completed_at: nil)}

  def completed?
    !completed_at.blank?
  end
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
  has_many :todo_items

  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  validates :description, presence: true
  validates :description, length: { minimum: 6 }

  def has_completed_items?
    todo_items.complete.size > 0
  end

  def has_incomplete_items?
    todo_items.incomplete.size > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todolist
  def index

  end

  def new

    @todo_item = @todolist.todo_items.new
  end

  def create

    @todo_item = @todolist.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = 'Added todo item'
      redirect_to todolist_todo_items_path
    else
      flash[:error] = 'There was a problem/error adding that todo item'
      render action: :new
    end
  end

  def complete
    @todo_item = @todolist.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todolist_todo_items_path, notice: 'Todo Item marked as complete'
  end

  def edit

    @todo_item = @todolist.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todolist.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = 'Saved todo item'
      redirect_to todolist_todo_items_path
    else
      flash[:error] = 'There was a problem/error adding that todo item'
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todolist.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = 'Item was deleted'
    else
      flash[:error] = 'ERROR: Item could not be deleted'
    end
    redirect_to todolist_todo_items_path
  end

  def url_options
    {todolist_id: params[:todolist_id]}.merge(super)
  end

  private
  def find_todolist
    @todolist = Todolist.find(params[:todolist_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: 'Todolist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todolist }
      else
        format.html { render action: 'new' }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="nav">
      <h1><%= link_to 'TodoList', root_path %></h1>
      <ul>
        <li><%= link_to 'Todo Lists', todolists_path %></li>
      </ul>
      <br class="clear" />
    </div>

    <% flash.each do |type, message| %>
    <div class="alert flash <%= type %>">
      <%= message %>
    </div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

      <ul>
        <% @todo_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit 'Save' %>

app/views/todo_items/edit.html.erb
<h1><%= @todolist.title %> - Editing Todo List Item</h1>

<%= form_for [@todolist, @todo_item] do |form| %>
    <%= render partial: form %>
<% end %>

app/views/todo_items/index.html.erb
<h1><%= @todolist.title %></h1>

<table class="todo_items">
  <thead>
  <tr>
    <th width="25%">Completed?</th>
    <th width="65%">Content</th>
    <th width="10%">Functions</th>
  </tr>
  </thead>
  <% @todolist.todo_items.each do |todo_item| %>
    <tr id="<%= dom_id(todo_item) %>">
      <% if todo_item.completed_at.blank? %>
          <td><%= link_to 'Mark Completed', complete_todolist_todo_item_path(todo_item), method: :patch %></td>
      <% else %>
          <td><%= todo_item.completed_at %></td>
      <% end %>

      <td><%= todo_item.content %></td>

      <td><%= link_to 'Edit', edit_todolist_todo_item_path(todo_item) %>
      <%= link_to 'Destroy', todolist_todo_item_path(todo_item), method: :delete, data: {confirm: 'Are you sure ?'}  %></td>

    </tr>
  <% end %>
</table>

<p><%= link_to 'New Todo Item', new_todolist_todo_item_path %></p>

app/views/todo_items/new.html.erb
<h1><%= @todolist.title %> - Editing Todo List Item</h1>
<%= form_for [@todolist, @todo_item] do |form| %>
    <%= render partial: form %>
<% end %>

app/views/todolists/_form.html.erb
<%= form_for(@todolist) do |f| %>
  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% @todolist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<!--<h1>Listing todolists</h1>-->

<!--<table>-->
  <!--<thead>-->
    <!--<tr>-->
      <!--<th>Title</th>-->
      <!--<th>Description</th>-->
      <!--<th></th>-->
      <!--<th></th>-->
      <!--<th></th>-->
      <!--<th></th>-->
    <!--</tr>-->
  <!--</thead>-->

  <!--<tbody>-->
    <!--<% @todolists.each do |todolist| %>-->
      <!--<tr id="<%= dom_id(todolist) %>">-->
        <!--<td><%= todolist.title %></td>-->
        <!--<td><%= todolist.description %></td>-->
        <!--<td><%= link_to 'Show', todolist %></td>-->
        <!--<td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>-->
        <!--<td><%= link_to 'Destroy', todolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <!--<td><%= link_to 'List Items', todolist_todo_items_path(todolist) %> </td>-->
      <!--</tr>-->
    <!--<% end %>-->
  <!--</tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Todolist', new_todolist_path %>-->


<h1>Todo Lists</h1>


<% @todolists.each do |todolist| %>
    <div class="todo_list" id="<%= dom_id(todolist) %>">
      <h2><%= todolist.title %></h2>
      <p><%= todolist.description %></p>
      <ul class="functions">
        <li><%= link_to "List Items", todolist_todo_items_path(todolist) %></li>
        <li><%= link_to 'Show', todolist %></li>
        <li><%= link_to 'Edit', edit_todolist_path(todolist) %></li>
        <li><%= link_to 'Destroy', todolist, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
      <br class="clear" />
    </div>
<% end %>

<br>

<%= link_to 'New Todo list', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New todolist</h1>

<%= render 'form' %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
  <!--<strong>Title:</strong>-->
  <!--<%= @todolist.title %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Description:</strong>-->
  <!--<%= @todolist.description %>-->
<!--</p>-->

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<!--<%= link_to 'Back', todolists_path %>-->





<h1><%= @todolist.title %></h1>

<h2><%= @todolist.description %></h2>

<% if @todolist.has_incomplete_items? %>
    <h3>Incomplete Items:</h3>

    <ul>
      <% @todolist.todo_items.incomplete.each do |todo_item| %>
          <li><%= todo_item.content %></li>
      <% end %>
    </ul>
<% end %>

<% if @todolist.has_completed_items? %>
    <h3>Complete Items:</h3>

    <ul>
      <% @todolist.todo_items.complete.each do |todo_item| %>
          <li><%= todo_item.content %></li>
      <% end %>
    </ul>
<% end %>

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<%= link_to 'Back', todolists_path %>